server:
  build: .
  dockerfile: server.Dockerfile
  links:
    - mysql
    - auth
    - redis
  ports:
    - "8080:8080"
  entrypoint: ./server
  command: -db server:password@tcp(mysql:3306)/quotes?parseTime=true -auth http://auth:8081 -redis redis:6379
auth:
  build: .
  dockerfile: auth.Dockerfile
  entrypoint: ./auth
  command: user1 user2
mysql:
  volumes:
    - ./mysqlsetup:/docker-entrypoint-initdb.d/
  image: mariadb:10.1.10
  ports:
    - "3306:3306"
  environment:
    - TERM=dumb
    - MYSQL_ALLOW_EMPTY_PASSWORD="true"
  command: mysqld --innodb_file_per_table
redis:
  image: redis:alpine
  ports:
    - "6379:6379"
